# Database connection settings
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.datasource.url=jdbc:postgresql://localhost:5432/FileUpload
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.open-in-view=false
spring.thymeleaf.check-template-location=false

jwt.secret=bW9uZ29kYmtleWZvcmphdmFzcHJpbmdiMDAxMjM0NTY3ODk=
jwt.expiration=86400000


